export const MAX_BOOKMARKS = 100;
export const BOOKMARKS_FIRST_LOAD_SAMPLE_SIZE = 10;
export const DELAY_BETWEEN_LOAD_SAMPLE_TO_LOAD_ALL_MS = 100;
export const MAX_SHORTCUT_LENGTH = 3;
export const MAX_MULTI_SHORTCUTS_TO_DISPLAY = 40;
